### PR TITLE
Integrate existing unit tests

### PR DESCRIPTION
**Pull request by xkbeyer**
Integrated already existing unit tests into the cmake build..
- fw
- project

Enable azure pipe line for windows. However, this might need some more work. I'll use this pr to test (and debug) the pipe line.
So, the pr should not be mergred before either the pipe line is fixed or it is disabled again in case I don't find a way to fix it.

### CODE REVIEW

**Comment by PeterBindels-TomTom** [comment]
Hope you can figure out the Windows thing. I don't even know where to start with that one.

**Comment by xkbeyer** [comment]
The last commit fixed it. The problem was the vcpkg submodule of 2019. The bootstrap ps1 checked for vs until 2019 and windows-latest uses vs2022. I Updated vcpkg to the current master.

**Comment by PeterBindels-TomTom** [comment]
Ready to merge?

**Comment by xkbeyer** [comment]
Yes.

**Pull request merged**
