### PR TITLE
Remove --start-group option.

### PR DESCRIPTION
**Pull request by hl4**
It's strange.start-group is not supported by clang on mac os for long time (back to 2014?), did anyone find the compile error?

### CODE REVIEW

**Comment by dascandy** [comment]
This is probably a remainder from me copying the Clang implementation from GCC. Thanks for finding this.

**Comment by dascandy** [comment]
Does this still work for cyclic dependencies though, or do we need some other flag for that on Clang?

**Comment by dascandy** [comment]
... Oh. This depends on the linker, which may be different for Apple. Can you find out what linker you're using?

**Comment by hl4** [comment]
I am not sure about cyclic dependencies. 
I uses the default toolset with macos/mojave, the linker reports:
```
ld -v
@(#)PROGRAM:ld  PROJECT:ld64-409.12
BUILD 17:47:51 Sep 25 2018
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 10.0.0, (clang-1000.10.44.4) (static support for 21, runtime is 21)
TAPI support using: Apple TAPI version 10.0.0 (tapi-1000.10.8)
```

**Comment by dascandy** [comment]
Based on your inputs during the major duplication removal I moved this to a separate file and removed it there. Thank you for bringing this to my attention. Can you confirm the current version works for you?

**Comment by hl4** [comment]
I found it is not working. I removed the two more line again based on main trunk.

**Comment by dascandy** [comment]
Thanks! Merged your commit, you should be able to use baseline from now on.

**Pull request merged**
